language: go
sudo: required
go:
  - 1.7.4
  - tip
os:
  - linux
install:
  - go get github.com/mattn/goveralls
  - go get github.com/kardianos/govendor
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - govendor test -race +local
